"""CLI entry point: build the accounts-payable forecast workbook from
today's supplier statement PDFs.

Update SUPPLIER_CONFIGS below with your real supplier codes - the
values here are placeholders matching the synthetic sample data
generated by scripts/generate_sample_data.py.
"""

########## Step 1: Imports ##########
from ap_forecast_automation.config import FinanceSettings, STORE_BANK_COLUMNS
from ap_forecast_automation.ap_forecast import SupplierStatementConfig, run



########## Step 2: One entry per supplier - bank_name removed, that's now company-wide ##########
SUPPLIER_CONFIGS = [
    SupplierStatementConfig(key="ACME", code_length=4, sheet_name="Acme"),
    SupplierStatementConfig(key="NWIND", code_length=5, sheet_name="Northwind"),
]


########## Step 3: Entry point ##########
if __name__ == "__main__":
    output_path = run(FinanceSettings(), SUPPLIER_CONFIGS, STORE_BANK_COLUMNS)
    print(f"AP forecast written to: {output_path}")